# Generated by Django 5.2.4 on 2025-08-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('item', models.CharField(choices=[('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('CPU', 'CPU'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Monitor', 'Monitor'), ('Other', 'Other')], max_length=50)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('config', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaint_images/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobcard.complaint')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='jobcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='jobcard.jobcard'),
        ),
    ]
