# Generated by Django 5.0.2 on 2025-08-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintimage',
            name='complaint',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='notes',
            new_name='complaint_description',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jobcard_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobcard.jobcard')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='ComplaintImage',
        ),
    ]
