# Generated by Django 5.2.4 on 2025-08-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0002_remove_complaintimage_complaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='complaint_description',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='complaint_notes',
        ),
        migrations.CreateModel(
            name='JobCardComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='jobcard.jobcard')),
            ],
        ),
    ]
