# Generated by Django 5.2.4 on 2025-08-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0003_remove_jobcard_complaint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='complaint_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JobCardComplaint',
        ),
    ]
