# Generated by Django 5.2.4 on 2025-08-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0004_jobcard_complaint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='complaints_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcardimage',
            name='complaint_index',
            field=models.IntegerField(default=0),
        ),
    ]
