# Generated by Django 5.2.4 on 2025-08-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0005_jobcard_complaints_data_jobcardimage_complaint_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='complaints_data',
        ),
        migrations.RemoveField(
            model_name='jobcardimage',
            name='complaint_index',
        ),
    ]
