# Generated by Django 5.2.4 on 2025-08-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0006_remove_jobcard_complaints_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('sent_to_technician', 'Sent to Technician'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='logged', max_length=20),
        ),
    ]
