# Generated by Django 5.2.4 on 2025-08-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0007_jobcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('logged', 'Logged'), ('sent_technician', 'Sent To Technician'), ('pending', 'Pending'), ('completed', 'Completed'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='logged', max_length=20),
        ),
    ]
